src/core/JWEditor.ts, src/core/stores/VDocument.ts, src/core/stores/VNode.ts, src/core/utils/BasicHtmlRenderingEngine.ts, src/core/utils/Format.ts, src/core/utils/Parser.ts, src/core/utils/Renderer.ts, src/core/utils/VDocumentMap.ts, src/plugins/DevTools/DevTools.xml, src/plugins/DevTools/components/InspectorComponent.ts
Also includes some related improvements.
This is the first part of a split of https://github.com/odoo-dev/jabberwock/pull/7 into two PRs.
=> [POC] Renderer: first version of a basic renderer

examples/index/index.css, examples/index/index.ts, src/core/JWEditor.ts, src/core/stores/VDocument.ts, src/core/stores/VNode.ts, src/core/stores/VRange.ts, src/core/utils/BasicHtmlRenderingEngine.ts, src/core/utils/CorePlugin.ts, src/core/utils/EventNormalizer.ts, src/core/utils/Renderer.ts, src/plugins/DevTools/DevTools.css, src/plugins/DevTools/DevTools.xml, src/plugins/DevTools/components/InfoComponent.ts, src/plugins/DevTools/components/TreeComponent.ts
This commit contains the missing commits from https://github.com/odoo-dev/jabberwock/pull/24, as well as a commit to hide the range nodes when traversing the VDocument, and a couple more fixes that were required along the way.
=> Miscellaneous fixes and improvements

packages/core/src/BasicHtmlRenderingEngine.ts, packages/core/src/CorePlugin.ts, packages/core/src/JWEditor.ts, packages/core/src/Parser.ts, packages/core/src/Renderer.ts, packages/core/src/VDocument.ts, packages/core/src/VDocumentMap.ts, packages/core/src/VNodes/CharNode.ts, packages/core/src/VNodes/LineBreakNode.ts, packages/core/src/VNodes/RangeNode.ts, packages/core/src/VNodes/RootNode.ts, packages/core/src/VNodes/SimpleElementNode.ts, packages/core/src/VNodes/VNode.ts, packages/core/src/VRange.ts, packages/core/test/Parser.test.ts, packages/core/test/VNodes.test.ts, packages/plugin-devtools/assets/DevTools.xml, packages/plugin-devtools/src/components/InfoComponent.ts, packages/plugin-devtools/src/components/InspectorComponent.ts, packages/plugin-devtools/src/components/PathComponent.ts, packages/plugin-devtools/src/components/TreeComponent.ts, packages/plugin-youtube/src/VNodes/YoutubeNode.ts, packages/utils/src/Predicates.ts, packages/utils/test/testUtils.test.ts
add tests: 100% coverage for VNodes
=> Master node classes age tests chm

packages/core/src/VNode.ts
This reimplements the `isBefore` method of `VNode`, which aims at determining whether a given node is first in the traversal of the tree (depth first, pre-order). Before this, the method was implemented naively, traversing the entire tree.
The new method is very efficient, which could justify removing the `direction` property of `VRange` in favor of a simple call to this. In the worst case scenario we need only traverse the ancestors of both
nodes all the way to the root.
Here's an explanation:
1. Generate the ancestors paths of each VNode up to the root.
2. Compare the ancestors paths starting by the root:
1. If both are the same, move on to the next ancestors in the paths.
2. If one of the ancestors is undefined, then the VNode that
originally generated this path is itself part of the …
=> [𝐼𝑀𝒫] 𝒱𝒩𝑜𝒹𝑒: 𝓇𝑒𝒾𝓂𝓅𝓁𝑒𝓂𝑒𝓃𝓉 𝒾𝓈𝐵𝑒𝒻𝑜𝓇𝑒 𝒾𝓃 𝒶𝓃 𝑒𝒻𝒻𝒾𝒸𝒾𝑒𝓃𝓉 𝓌𝒶𝓎

packages/plugin-devtools/assets/DevTools.xml, packages/plugin-devtools/src/components/CommandsComponent.ts, packages/plugin-devtools/src/components/InfoComponent.ts, packages/plugin-devtools/src/components/InspectorComponent.ts, packages/plugin-devtools/src/components/TreeComponent.ts, packages/plugin-devtools/test/devtools.test.ts, packages/utils/src/testUtils.ts
add coverage for devtools + fix (remove VNode from owl's useState)
=> Master test devtools chm

packages/core/test/todo.md
When implementing the tests for the delete, backspace and enter keys,
certain tests from we3 had to be skipped. Please check these whenever a
new feature is implemented, and convert the tests that have become
relevant thanks to your feature, if any.
This is meant to be merged right after delete, backspace and enter tests.
=> [ADD] Doc: information on which tests were not converted yet

examples/demo/demo.ts, examples/jabberwocky/jabberwocky.ts, packages/core/src/EventNormalizer.ts, packages/core/src/JWEditor.ts, packages/core/test/JWeditor.test.ts, packages/owl-ui/src/OwlUI.ts, packages/plugin-bold/src/BoldButtons.ts, packages/plugin-char/src/Char.ts, packages/plugin-heading/src/HeadingButtons.ts, packages/plugin-indent/src/IndentButtons.ts, packages/plugin-inline/src/Inline.ts, packages/plugin-italic/src/ItalicButtons.ts, packages/plugin-list/src/ListButtons.ts, packages/plugin-toolbar/assets/Toolbar.css, packages/plugin-toolbar/assets/Toolbar.xml, packages/plugin-toolbar/src/Toolbar.ts, packages/plugin-toolbar/src/ToolbarUI.ts, packages/plugin-toolbar/src/components/ToolbarComponent.ts, packages/plugin-underline/src/UnderlineButtons.ts, packages/utils/src/errors.ts
=> [ADD] Toolbar: basic static toolbar

examples/demo/index.html, examples/jabberwockipedia/index.html, examples/jabberwocky/index.html, package.json, packages/plugin-heading/src/Heading.ts, tsconfig.json, webpack.config.js
=> [IMP] build the examples

bundles/BasicEditor.ts, examples/demo/demo.ts, examples/demo/demo.xml, packages/plugin-align/src/Align.ts, packages/plugin-align/src/AlignButtons.ts, packages/plugin-align/test/Align.test.ts, packages/plugin-devtools/test/devtools.test.ts
=> [ADD] Align: align text left/center/right/justify

examples/demo/demo.css, examples/demo/demo.xml, karma.conf.js, packages/core/src/VNodes/Children.ts, packages/core/src/VRange.ts, packages/plugin-devtools/assets/DevTools.css, packages/plugin-devtools/assets/DevTools.xml, packages/plugin-devtools/src/components/DevToolsComponent.ts, packages/plugin-devtools/test/devtools.test.ts, packages/plugin-dom/src/DefaultDomRenderer.ts, packages/plugin-dom/src/DomRenderingEngine.ts, packages/plugin-list/src/ListItemDomRenderer.ts, packages/plugin-renderer/src/AbstractRenderer.ts, packages/plugin-renderer/src/RenderingEngine.ts, packages/plugin-table/src/Table.ts, packages/plugin-table/src/TableCellDomParser.ts, packages/plugin-table/src/TableCellDomRenderer.ts, packages/plugin-table/src/TableCellNode.ts, packages/plugin-table/src/TableDomParser.ts, packages/plugin-table/src/TableDomRenderer.ts, packages/plugin-table/src/TableNode.ts, packages/plugin-table/src/TableRowDomParser.ts, packages/plugin-table/src/TableRowDomRenderer.ts, packages/plugin-table/src/TableRowNode.ts, packages/plugin-table/test/Table.test.ts, packages/plugin-table/test/tableTestTemplate.xml, packages/plugin-table/test/tableTestUtils.ts, packages/utils/src/isBlock.ts, packages/utils/src/testUtils.ts
Handle general table behavior.
Limitations:
- /!\ Does not include `unbreakable` so selection/backspace/delete/enter are momentarily broken in a table.
- Does not handle `<colgroup>`, `<tfoot>` and `<caption>`
- Add row/column only collapsed
=> [𝔸𝔻𝔻] 𝕍ℕ𝕠𝕕𝕖: 𝕋𝕒𝕓𝕝𝕖

bundles/BasicEditor.ts, examples/demo/demo.ts, examples/demo/demo.xml, packages/core/test/todo.md, packages/plugin-devtools/test/devtools.test.ts, packages/plugin-heading/src/Heading.ts, packages/plugin-heading/test/Heading.test.ts, packages/plugin-pre/src/Pre.ts, packages/plugin-pre/src/PreButtons.ts, packages/plugin-pre/src/PreDomParser.ts, packages/plugin-pre/src/PreDomRenderer.ts, packages/plugin-pre/src/PreNode.ts, packages/plugin-pre/test/Pre.test.ts, packages/utils/src/formattingSpace.ts
Todo: tests.
Question: is it important to render the contents of the `<pre>` as is ? - should we change rendering of chars in `<pre>` so that multiple spaces don't insert `\u00A0`s?
=> [ADD] Plugins: Pre

packages/plugin-char/src/CharXmlDomParser.ts, packages/plugin-pre/src/Pre.ts, packages/plugin-pre/src/PreCharHtmlDomRenderer.ts, packages/plugin-pre/src/PreHtmlDomRenderer.ts, packages/plugin-pre/src/PreSeparatorHtmlDomRenderer.ts, packages/plugin-pre/src/PreXmlDomParser.ts, packages/plugin-pre/test/Pre.test.ts
This PR addresses issue https://github.com/odoo-dev/jabberwock/issues/147
=> Improve Pre

packages/core/src/VNodes/AbstractNode.ts, packages/plugin-heading/src/Heading.ts, packages/plugin-list/src/List.ts, packages/plugin-pre/src/Pre.ts
This replaces several instances of duplicated code, addressing issue #131.
=> [REF] VNode: add a method to replace a node with another

examples/odoo/index.html, examples/odoo/odoo.ts, examples/odoo/odoo.xml, examples/utils/editor.css, packages/plugin-odoo-video/src/OdooVideo.ts, packages/plugin-odoo-video/src/OdooVideoHtmlDomRenderer.ts, packages/plugin-odoo-video/src/OdooVideoNode.ts, packages/plugin-odoo-video/src/OdooVideoXmlDomParser.ts, packages/plugin-odoo-video/test/OdooVideo.test.ts
In Odoo, video information are saved within a div that has
the class "media_iframe_video" with an attribute "data-oe-expression".
=> [IMP] OdooVideo: parse/render odoo video

packages/plugin-link/src/components/LinkComponent.ts
=> [FIX] Link: ensure link dialog fully closes on save

examples/demo/demo.ts, examples/demo/demo.xml, examples/jabberwocky/jabberwocky.ts, packages/plugin-list/src/List.ts, packages/plugin-list/src/ListButtons.ts, packages/plugin-list/src/ListHtmlDomRenderer.ts, packages/plugin-list/src/ListItemHtmlDomRenderer.ts, packages/plugin-list/src/ListItemXmlDomParser.ts, packages/plugin-list/src/ListNode.ts, packages/plugin-list/src/ListXmlDomParser.ts, packages/plugin-list/src/ui/checklist.css, packages/plugin-list/test/List.test.ts
=> [ADD] List: introduce the checklist feature

bundles/BasicEditor.ts, examples/demo/demo.ts, examples/jabberwockipedia/jabberwockipedia.ts, examples/jabberwocky/jabberwocky.ts, examples/layout/layout.ts, examples/odoo/odoo.ts, packages/core/test/VNodes.test.ts, packages/plugin-devtools/test/devtools.test.ts, packages/plugin-dom-editable/src/DomEditable.ts, packages/plugin-dom-editable/test/DomEditable.test.ts, packages/plugin-dom-follow-range/test/FollowRange.test.ts, packages/plugin-dom-layout/src/ui/DomLayoutEngine.ts, packages/plugin-dom-layout/test/DomLayout.test.ts, packages/plugin-keymap/test/Keymap.test.ts, packages/plugin-parser/test/Parser.test.ts, packages/plugin-shadow/test/DomShadow.test.ts, packages/utils/src/DomMap.ts, packages/utils/src/configuration.ts, packages/utils/src/testUtils.ts
The plugin add the feature of contentEditable with event normalization but don't have any target by
default.
=> [IMP] DomEditable is free of components

.gitignore, packages/core/src/Modifier.ts, packages/plugin-char/src/Char.ts, packages/plugin-dialog/src/DialogZoneDomObjectRenderer.ts, packages/plugin-dialog/test/Dialog.test.ts, packages/plugin-dom-layout/src/DomLayoutEngine.ts, packages/plugin-dom-layout/test/DomLayout.test.ts, packages/plugin-inline/src/Inline.ts, packages/plugin-layout/src/Layout.ts, packages/plugin-layout/src/LayoutEngine.ts, packages/plugin-link/src/Link.ts, packages/plugin-link/src/LinkFormat.ts, packages/plugin-link/src/components/LinkComponent.ts, packages/plugin-link/test/Link.test.ts, packages/plugin-xml/src/Attributes.ts
This property is used to determine if a modifier should be kept after a break line or not.
see issue #187
=> [IMP] Modifier, Link : Add a preserve property , better behaviors of Link format

packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts, packages/plugin-odoo/src/Odoo.ts, packages/plugin-toolbar/assets/Toolbar.css
Linked odoo PR : https://github.com/odoo-dev/odoo/pull/297
=> [IMP] add a discard button in the menu for the odoo integration

packages/core/src/VRange.ts, packages/plugin-heading/test/Heading.test.ts
Handles issue https://github.com/odoo-dev/jabberwock/issues/183
=> [FIX] VRange: do not return the next container after a triple click

packages/plugin-devtools/src/components/CommandsComponent.ts, packages/plugin-devtools/src/components/ShortcutsComponent.ts, packages/plugin-dom-layout/src/DomLayoutEngine.ts, packages/plugin-dom-layout/src/DomReconciliationEngine.ts, packages/plugin-dom-layout/test/DomLayout.test.ts, packages/plugin-list/src/ListDomObjectRenderer.ts, packages/plugin-renderer-dom-object/src/DomObjectRenderingEngine.ts, packages/plugin-renderer/src/AbstractRenderer.ts, packages/utils/src/utils.ts, tsconfig.json
Currently Odoo is configured to suppot maximum es2017.
=> [IMP] Core: downgrage build to es2017

examples/resizable/index.html, examples/resizable/resizable.ts, packages/bundle-basic-editor/basicLayout.css, packages/bundle-basic-editor/basicLayout.xml, packages/plugin-resizer/assets/Resizer.css, packages/plugin-resizer/src/Resizer.ts, packages/plugin-resizer/src/ResizerDomObjectRenderer.ts, packages/plugin-resizer/src/ResizerNode.ts
Add a small bar on the bottom of the editor that allow the user to resize the editor with drag and drop
=> [ADD] Resizer: tool to allow easy editor resising

packages/plugin-devtools/src/components/InspectorComponent.ts
Handles https://github.com/odoo-dev/jabberwock/issues/208.
=> [ADD] Devtools: auto scroll inspector to selected node

packages/utils/src/formattingSpace.ts, packages/utils/test/formattingSpace.test.ts
Also fix some tour bug in odoo integration.
=> [IMP] more robust management for space formating based on HTML sources

packages/bundle-odoo-website-editor/odoo-integration.ts, packages/core/src/Mode.ts, packages/plugin-renderer-dom-object/src/DomObjectRenderingEngine.ts
Odoo pr: https://github.com/odoo-dev/odoo/pull/317
I'm sure we will discuss about the name ;)
=> [IMP] RendererDomObject: configure BR rendering

packages/bundle-basic-editor/BasicEditor.ts, packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts, packages/plugin-textarea/src/Textarea.ts, packages/plugin-textarea/src/TextareaDomObjectRenderer.ts, packages/plugin-textarea/src/TextareaNode.ts, packages/plugin-textarea/src/TextareaXmlDomParser.ts, packages/plugin-textarea/test/Textarea.test.ts, packages/utils/src/formattingSpace.ts, packages/utils/test/formattingSpace.test.ts
Need it in odoo to avoid `<br>` inside a textarea as it is an `AtomicNode`
=> [IMP] Textarea: introduce textarea node

packages/bundle-basic-editor/BasicEditor.ts, packages/plugin-code/src/Code.ts, packages/plugin-code/src/CodeButtonDomObjectRenderer.ts, packages/plugin-code/src/CodeViewDomObjectRenderer.ts, packages/plugin-code/src/CodeViewNode.ts
https://drive.google.com/file/d/1bnkZI4Eco260mm4Mmdjo5lCNuLU2PNqf/view
=> [ADD] Code: view and edit the document's html

packages/plugin-align/src/Align.ts, packages/plugin-bold/src/Bold.ts, packages/plugin-heading/src/Heading.ts, packages/plugin-italic/src/Italic.ts, packages/plugin-list/src/List.ts, packages/plugin-pre/src/Pre.ts, packages/plugin-underline/src/Underline.ts
The toolbar is very very slow for the selection because the method
'targetedNodes' is very slow (lot of call and compare with 'areSameAs' and
'isSameAs' modifier very slow methods.
=> [IMP] *: Very significant speed improvement.

examples/layout/main.xml, packages/plugin-iframe/test/iframe.test.ts
Issue: setSelection not colapsed does not work in example theme with
shadow in iframe in shadown.
=> [FIX] Iframe: add test and fix example

packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts, packages/bundle-odoo-website-editor/odooLayout.css, packages/plugin-html/src/DefaultHtmlTextParser.ts, packages/plugin-iframe/src/IframeDomObjectRenderer.ts
Fix parsing Html/text autoCloseRegExp (wrong for link with \ inside data).
Fix iframe rendering, don't use map that return a versionable instance.
=> [IMP] OdooWebsite: add theme: mobile preview

packages/plugin-fontawesome/src/FontAwesomeDomObjectRenderer.ts, packages/plugin-odoo/src/OdooFontAwesomeDomObjectRenderer.ts
+ add data for odoo font awesome replacement
link to odoo PR : https://github.com/odoo-dev/odoo/pull/373
=> [IMP] fontAwesome auto select icon when click

packages/bundle-odoo-website-editor/odoo-integration.ts, packages/core/src/VNodes/AbstractNode.ts, packages/core/test/VNodes.test.ts
Linked Odoo PR: https://github.com/odoo-dev/odoo/pull/375
=> [FIX] Odoo: properly replace an existing link

packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts, packages/plugin-dom-helpers/src/DomHelpers.ts, packages/plugin-iframe/src/IframeDomObjectRenderer.ts, packages/utils/src/polyfill.ts
On odoo, the snippet can be edited in mobile preview (iframe) and in
mass_mailing
=> [IMP] Iframe,OdooWebsiteEditor: better iframe event forwarding

packages/core/src/VRange.ts, packages/plugin-bold/src/Bold.ts, packages/plugin-char/src/Char.ts, packages/plugin-char/src/CharDomObjectRenderer.ts, packages/plugin-color/src/Color.ts, packages/plugin-inline/src/Inline.ts, packages/plugin-italic/src/Italic.ts, packages/plugin-link/src/LinkFormat.ts, packages/plugin-link/test/Link.test.ts, packages/plugin-textcolor/test/TextColor.test.ts, packages/plugin-underline/src/Underline.ts
Linked Odoo PR: https://github.com/odoo-dev/odoo/pull/376
=> [IMP] VRange: replace Inline.cache with VRange.modifiers

packages/bundle-basic-editor/BasicEditor.ts, packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts, packages/plugin-blockquote/src/Blockquote.ts, packages/plugin-code/src/Code.ts, packages/plugin-dom-follow-range/src/FollowRangeZoneDomObjectRenderer.ts, packages/plugin-heading/src/Heading.ts, packages/plugin-link/src/Link.ts, packages/plugin-odoo/src/Odoo.ts, packages/plugin-pre/src/Pre.ts, packages/plugin-strikethrough/src/Strikethrough.ts, packages/plugin-strikethrough/src/StrikethroughFormat.ts, packages/plugin-strikethrough/src/StrikethroughXmlDomParser.ts
Linked Odoo PR: https://github.com/odoo-dev/odoo/pull/377
=> [IMP] *: make a better floating toolbar, with matching features

packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts, packages/plugin-char/src/CharXmlDomParser.ts, packages/plugin-devtools/src/components/CommandsComponent.ts, packages/plugin-devtools/src/components/DevToolsComponent.ts, packages/plugin-devtools/src/components/InspectorComponent.ts, packages/plugin-dom-editable/src/EventNormalizer.ts, packages/plugin-dom-editable/src/MutationNormalizer.ts, packages/plugin-dom-editable/test/eventNormalizerUtils.ts, packages/plugin-dom-follow-range/src/FollowRangeZoneDomObjectRenderer.ts, packages/plugin-dom-layout/src/DomLayout.ts, packages/plugin-dom-layout/src/DomReconciliationEngine.ts, packages/plugin-iframe/src/IframeDomObjectRenderer.ts, packages/plugin-linebreak/src/LineBreakXmlDomParser.ts, packages/plugin-resizer/src/ResizerDomObjectRenderer.ts, packages/plugin-shadow/test/DomShadow.test.ts, packages/plugin-stylesheet/src/Stylesheet.ts, packages/plugin-theme/src/ThemeDomObjectRenderer.ts, packages/utils/src/Dom.ts, packages/utils/src/configuration.ts, packages/utils/src/formattingSpace.ts, packages/utils/src/polyfill.ts, packages/utils/src/testUtils.ts, packages/utils/src/utils.ts
+ refactoring to use only one normaliser instead of one instance by shadow
root or document iframe.
=> [FIX] DomEditable: trigger only once the command when use shadow/iframe

packages/plugin-odoo/src/OdooFontAwesomeDomObjectRenderer.ts
We need to retrieve the fontawesome at the time of the command
openMedia. Which is done in Odoo code.
=> [FIX] FontAwesome: remove params from fontawesome

packages/plugin-odoo-field/src/OdooField.ts, packages/plugin-odoo/src/OdooStructureNode.ts
Add info to OdooField and OdooStructure to be retrieved by Odoo to know
if the field has changed.
/!\ Don't forget to merge the odoo PR: https://github.com/odoo-dev/odoo/pull/380
=> [IMP] Odoo: add information when change

packages/plugin-dom-helpers/src/DomHelpers.ts
This implements a command that is roughly equivalent to `$.wrapAll(node.contents())` (as `helper.wrapContents(node)`).
Linked Odoo PR: https://github.com/odoo-dev/odoo/pull/383
=> [ADD] DomHelpers: helper to wrap the contents of a node ($.wrapAll)

packages/plugin-dom-layout/src/DomLayout.ts
=> [FIX] Dispatch hooks for @focus and @blur

packages/core/src/Dispatcher.ts, packages/core/src/JWEditor.ts, packages/plugin-devtools/test/devtools.test.ts, packages/plugin-dom-editable/test/DomEditable.test.ts, packages/plugin-dom-editable/test/EventManager.test.ts, packages/plugin-dom-layout/src/DomLayout.ts, packages/plugin-iframe/test/iframe.test.ts, packages/plugin-keymap/test/Keymap.test.ts, packages/plugin-shadow/test/DomShadow.test.ts
And remove the temporary range any time.
=> [FIX] Dispatcher: dispatch to all hooks even if there is no command

packages/plugin-odoo/src/Odoo.ts
Issue: in odoo shop, when the user change the add to card icon, the link
(with data-oe-model) are removed.
=> [FIX] Odoo: insertMedia keep previous modifiers

packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts, packages/plugin-dom-layout/src/ActionableDomObjectRenderer.ts, packages/plugin-history/src/History.ts, packages/plugin-layout/src/ActionableNode.ts
Linked Odoo PR: https://github.com/odoo-dev/odoo/pull/392
=> [ADD] OdooWebsiteEditor: history buttons

packages/plugin-dom-layout/test/DomLayout.test.ts, packages/plugin-fontawesome/src/FontAwesomeDomObjectRenderer.ts, packages/plugin-fontawesome/test/FontAwesome.test.ts, packages/plugin-odoo/src/OdooFontAwesomeDomObjectRenderer.ts
Related Odoo PR: https://github.com/odoo-dev/odoo/pull/403
=> [IMP] Fontawesome: only surround fa when close to range

packages/plugin-dom-helpers/src/DomHelpers.ts
Some dom nodes have a special `Attributes` class.
For instance, the node "LI" have ListItemAttributes.
The helper methods changing Attributes now take it into consideration.
=> [FIX] DomHelpers: Attributes depends on node

packages/bundle-odoo-website-editor/odoo-integration.ts, packages/plugin-resizer/assets/Resizer.css, packages/plugin-resizer/src/ResizerDomObjectRenderer.ts
Odoo Community PR: https://github.com/odoo/odoo/pull/60267
Odoo Enterprise PR: https://github.com/odoo/enterprise/pull/14201
=> [IMP] Resizer: prepare for use of Resizer in Odoo

packages/plugin-dom-helpers/src/DomHelpers.ts
Related Odoo PR: https://github.com/odoo/odoo/pull/60796
=> [ADD] DomHelpers: set class helper

packages/utils/src/Dom.ts, packages/utils/src/polyfill.ts
Addresses:
> [DMO] project: on EDIT mode on a task, try to log a note in fullscreen: clicking "Log" after writing the node does nothing and freezes the chatter !
=> [FIX] polyfill: ensure shadow caret position fallback in contenteditable
