odoo-dev/jabberwock

src/plugins/DevTools/DevTools.xml
src/plugins/DevTools/components/DevToolsComponent.ts
src/ui/OwlUIComponent.ts

Keep DevTool's height, open tab etc. between refreshes. Handy when debugging with auto-refresh.

[ADD] DevTools: use localstorage for basic state

---

src/plugins/DevTools/DevTools.xml
src/plugins/DevTools/components/TreeComponent.ts

When a node is selected (e. g. from the sidebar), unfold all the
components (TreeComponent) if it's node is present in the selected path.

[IMP] Unfold node in debugger

---

src/core/utils/EventNormalizer.ts

... instead of the top window's document (which fails with iframes and shadow doms)

[FIX] EventNormalizer: bind events to ownerDocument

---

src/core/stores/VDocument.ts
src/core/stores/VNode.ts
src/core/stores/VRange.ts
src/core/utils/Predicates.ts
src/core/utils/Renderer.ts
src/plugins/DevTools/components/TreeComponent.ts

To avoid having too much isWhatever functions on the VNode class and
to be able to use them as traversal predicates directly, without having
to use a useless arrow function like node => node.isWhatever().
Note: I had to extract `VNodeType` out of `VNode` because`VNode` depended on `Predicates` to implement its method but `Predicates` depended on `VNode` because it needed `VNodeType`.

[ADD] Utils: add predicates library

---

karma.conf.js

Before this commit, the coverage always happened and in some
circumstances, made development harder:
- The coverage add clutter in the source code
- The coverage increase the build time
Now to launch the tests with coverage, use the following command:
```bash
npm test --coverage
```

[IMP] Add coverage option to npm "test"

---

packages/core/src/EventManager.ts
packages/core/src/JWEditor.ts
packages/core/src/Parser.ts
packages/core/src/VDocumentMap.ts
packages/core/src/VNode.ts
packages/core/src/VRange.ts
packages/core/test/Parser.test.ts
packages/core/test/Renderer.test.ts
packages/core/test/VDocument.test.ts
packages/utils/src/testUtils.ts
packages/utils/src/utils.ts
packages/utils/test/testUtils.test.ts

This converts all currently relevant delete/backspace tests from we3. Below is the list
all tests that are not yet relevant, as well as two skipped tests.
All issues revealed by these tests are fixed with this PR.
1. [Forward](#forward)
1. [Skipped](#f-skipped)
1. [Two function calls -> redundant](#f-s-tfc)
2. [To convert later](#f-todo)
1. [Classes](#f-t-classes)
2. [PRE](#f-t-pre)
3. [Lists](#f-t-lists)
4. [Tables](#f-t-tables)
5. [SPAN](#f-t-span)
6. [Pictograms](#f-t-pictograms)
7. [HR](#f-t-hr)
8. [Integration](#f-t-integration)
2. [Backward](#backward)
1. [Skipped](#b-skipped)
1. [Two function calls -> redundant](#b-s-tfc)
2. [To convert later](#b-todo)
1. [Classes](#b-t-classes)
2. [PRE](#b-t-pre)
3. [Lists](#b-t-lists)
4. [Tables](#b-t-tables)
5. [SPAN](#b-t-span)
6. …

Add delete/backspace tests and fix related issues

---

packages/core/src/Parser.ts
packages/core/test/VDocument.test.ts
packages/utils/src/testUtils.ts

This implements all currently relevant tests from we3 for the enter key (with and without the shift key) and more.
All tests that are yet to be converted are listed below.
1. [Classes](#classes)
2. [Buttons](#buttons)
3. [Lists](#lists)
4. [SPAN](#span)
5. [Integration](#integration)
Note: The tests that are commented out were found as is in we3. They were either "todo" or "toremove"...
```javascript
{
name: "in p (other-p > span.a before - p > span.b after): ENTER at beginning",
content: "<p><span class=\"a\">dom to</span></p><p><span class=\"b\">◆edit</span></p>",
steps: [{
key: 'ENTER',
}],
test: "<p><span class=\"a\">dom to</span></p><p><span class=\"b\"><br/></span></p><p><span class=\"b\">◆edit</span></p>",
},
{
name: "in p (other-p > span.a before - p > span.b after): ENTER -> 'a' …
```

[ADD] Tests: enter

---

packages/core/src/VNodes/VNode.ts
packages/core/test/VNodes.test.ts

This adds methods to return a list of a VNode's ancestors/descendants, with a predicate like for[next|previous]Siblings.

[ADD] VNode: ancestors and descendants functions

---

packages/core/src/EventManager.ts
packages/core/src/JWEditor.ts
packages/core/src/JWPlugin.ts
packages/core/src/Keymap.ts
packages/core/test/JWeditor.test.ts
packages/core/test/Keymap.test.ts
packages/plugin-char/Char.ts
packages/plugin-list/List.ts
packages/utils/src/testUtils.ts

This keymap allows to:
- specify shortcuts from the config of the editor
- specify default shortcuts for plugins
- specify shortcuts and default shortcuts depending on the platform (mac
or others)
- specify shortucts with javascript event 'key' or 'code'

[IMP] core: Add a keymap mechanism

---

bundles/BasicEditor.ts
packages/core/src/EventManager.ts
packages/core/src/VRange.ts
packages/plugin-devtools/test/devtools.test.ts
packages/plugin-indent/src/Indent.ts
packages/plugin-indent/test/Indent.test.ts

The indent command now acts like tab does in code editors.
We might want to move this into a Code plugin later when we
implement the standard paragraph/list indent behavior.
One of the issues of indent was the new `selectedNodes` semantic
which does not return nodes that are only partially selected.
To solve this, I added a `retractedNodes` function on VRange which
returns the nodes that would be retracted from the DFS traversal
algorithm when the VRange is seen as a retraction of the document
tree, which is in fact equivalent to the old `selectedNodes` behavior.

[FIX] Indent: fix indent behavior

---

packages/core/src/Dispatcher.ts
packages/core/src/JWEditor.ts
packages/core/src/JWPlugin.ts
packages/core/test/Dispatcher.test.ts
packages/plugin-devtools/assets/DevTools.xml
packages/plugin-devtools/src/components/CommandsComponent.ts

The previous version had generated confusion in the code.
Now, instead of having commands and handlers on plugin, there is only
commands.

[REF] core: refactor dispatcher to merge command and handlers

---

packages/plugin-devtools/assets/DevTools.css

This does not yet treat the deeper problem of the general stylesheet of DevTools but it's a symptomatic treatment of something bothersome on a daily basis: it prevents unreachable contents.

[FIX] DevTools: quickfix of problematic css

---

packages/core/src/JWEditor.ts
packages/core/test/JWeditor.test.ts
packages/utils/src/testUtils.ts

The plugins start is done in the editor's start. Therefore if a plugin is
added after, it is built (new) but the start method is never called.
Adding a throw prevents this kind of error from the developer.

[IMP] JWEditor: user can not change config when the editor is started

---

packages/core/src/EventNormalizer.ts
packages/core/test/EventNormalizerPointer.test.ts

Concerning the test, I see no reason why we should expect a `setSelection`. If @Goaman (who wrote the test) confirms then I believe we can merge as is.

[FIX] EventNormalizer: paste with context menu

---

packages/core/src/EventManager.ts

In a previous refactoring of the normalizer, the command
'insertLineBreak' was triggered by an action 'insertText' or
'insertHTML', now the normalizer send directly the action
'insertLineBreak'.

[FIX] EventNormalizer: restore insertLineBreak

---

packages/utils/src/testUtils.ts

When debugging only one test case, it is sometimes usefull to let the
container in the document. For instance, to inspect one value
of the `vDocument` through our debugger.

[IMP] utils: testEditor without stopping the editor

---

packages/plugin-link/src/LinkButtons.ts

Clicking in an empty element made the toolbar crash.
Addresses #172.

[FIX] Link: prevent the toolbar from crashing on click in empty element

---

packages/core/src/Modifiers.ts
packages/plugin-align/src/Align.ts
packages/plugin-backgroundcolor/test/BackgroundColor.test.ts
packages/plugin-char/src/Char.ts
packages/plugin-color/src/Color.ts
packages/plugin-dom-editable/test/DomEditable.test.ts
packages/plugin-fontawesome/test/FontAwesome.test.ts
packages/plugin-html/src/HtmlDomRenderingEngine.ts
packages/plugin-inline/src/Format.ts
packages/plugin-inline/src/Inline.ts
packages/plugin-inline/test/Inline.test.ts
packages/plugin-list/src/ListItemXmlDomParser.ts
packages/plugin-shadow/test/DomShadow.test.ts
packages/plugin-table/src/TableRowXmlDomParser.ts
packages/plugin-table/test/Table.test.ts
packages/plugin-table/test/tableTestUtils.ts
packages/plugin-textcolor/test/TextColor.test.ts
packages/plugin-xml/src/Attributes.ts
packages/plugin-xml/src/ClassList.ts
packages/plugin-xml/src/CssStyle.ts
packages/plugin-xml/src/XmlDomParsingEngine.ts
packages/plugin-xml/test/Xml.test.ts
packages/utils/src/utils.ts

[IMP] Attributes: introduce CssStyle and ClassList
Attributes `style` and `class` can be manipulated in an easier way
through the new classes `CssStyle` and `ClassList`, which exist on the
`style` and `classList` properties of `Attributes`.
Examples:
```ts
node.modifiers.get(Attributes).style.set('color', 'red');
node.modifiers.find(Attributes)?.style.get('color'); // returns 'red'
node.modifiers.get(Attributes).set('style', 'width: 500px; background-color: blue;');
node.modifiers.find(Attributes)?.style.length; // returns 2
node.modifiers.find(Attributes)?.style.get('width'); // returns '500px'
node.modifiers.find(Attributes)?.style.get('color'); // returns undefined
node.modifiers.find(Attributes)?.get('style'); // returns 'width: 500px; background-color: blue;' …
```

[IMP] Modifiers: introduce CSSStyle and ClassList

---

package.json
packages/plugin-owl/src/Owl.ts

Owl updated the Env interface by restricting the properties to be
more specific and introduced the "browser" property.
This commit explicitly bump the version number of Owl as well as
adding browser to our Owl plugin.

[FIX] Owl: bump version and add env browser

---

packages/plugin-dom-layout/src/ui/DomReconciliationEngine.ts
packages/plugin-dom-layout/test/DomLayout.test.ts

This fix, avoid to have error when we try to locate a VNode where the
rendering is altered and not inside the dom.
Fix also the re-insertion of node removed from alteration.

[FIX] dom-layout: long press bacspace can create an altered

---

packages/plugin-char/src/CharDomObjectRenderer.ts
packages/plugin-char/test/CharDomObjectRenderer.test.ts
packages/plugin-devtools/test/devtools.test.ts
packages/plugin-image/src/ImageDomObjectRenderer.ts
packages/plugin-inline/src/InlineFormatDomObjectRenderer.ts
packages/plugin-inline/test/Inline.test.ts
packages/plugin-pre/src/PreCharDomObjectRenderer.ts

To use nesting, you just have to inherit from the InlineDomObjectRenderer
class and override the renderNodes method without taking into account the
format. An option is added to create or not span for the attributes.

[IMP] Inline: can nest every inlineNode into format tag.

---

packages/plugin-table/src/TableXmlDomParser.ts
packages/plugin-table/test/Table.test.ts

We expect each row in a table to have the same number of cells. But when
we need to parse one that doesn't, we also don't want the system to
crash. To emulate what the browser does, this commit introduces empty
cells where they were missing, extrapolating on the inconsistent table
that is being parsed.

[FIX] Table: allow the parsing of a table with inconsistent cell numbers

---

karma.conf.js
test_index.ts

Before this commit, all individual test files were containing all the
source and sourcemap. Which created performance issues.
N test files where N big bundles.
Now all test files are all container within 1 big bundle.

[FIX] Tests: make them faster

---

packages/plugin-image/src/ImageDomObjectRenderer.ts

Without that fix, if we try to click on an image when the editor is
redrawing, it will generate a "double redraw".

[FIX] Image: click handler in mutex

---

packages/plugin-dom-editable/src/EventNormalizer.ts

In firefox, it is required to perfor this check because the TouchEvent
might not be present.

[FIX] DomEditable: check TouchEvent

---

examples/modes/modes.ts
packages/core/src/Core.ts
packages/core/src/JWEditor.ts
packages/core/src/Mode.ts
packages/core/test/Mode.test.ts
packages/plugin-devtools/assets/DevTools.css
packages/plugin-devtools/assets/DevTools.xml
packages/plugin-devtools/src/components/DevToolsComponent.ts
packages/plugin-devtools/src/components/ModesComponent.ts
packages/plugin-dom-editable/src/EventNormalizer.ts
packages/plugin-dom-editable/test/EventNormalizerKeyboard.test.ts

Up to this commit every rule property was set based on a cascading selector, which means the properties were always propagated to all descendants of the node matched by the selector. This makes sense for `editable` but caused issues with `breakable` and made little sense for `allowEmpty`.
This reorganizes the rule definition by introducing the `cascading` boolean (default: false).
Linked Odoo PR: https://github.com/odoo-dev/odoo/pull/339

[FIX] Mode: allow cascading and non-cascading rule properties

---

packages/core/src/Core.ts
packages/core/test/VDocument.test.ts
packages/plugin-list/test/List.test.ts

If a heading is preceded by an empty paragraph and we press backspace at the beginning of said heading, we want to simply move the heading up, we don't want it to become a paragraph. This commit addresses that issue so the behavior of `deleteBackward` and `deleteForward` follows the GSpec.

[IMP] Core: delete an empty container instead of merging into it

---

examples/demo-odoo-fields/demo-odoo-fields.ts
examples/demo/demo.ts
examples/jabberwockipedia/jabberwockipedia.ts
examples/jabberwocky/jabberwocky.ts
examples/layout/layout.ts
examples/modes/modes.ts
examples/odoo/odoo.ts
examples/resizable/resizable.ts
packages/plugin-toolbar/src/Toolbar.ts

If we need to style the toolbar completely, we must not include the
css in the toolbar itself.

[IMP] Remove styles from Toolbar

---

packages/plugin-dom-layout/src/DomReconciliationEngine.ts
packages/plugin-dom-layout/test/DomLayout.test.ts

Must detach callback for domObject complete redraw.
Issue: split a paragraph on firefox with some formatted and not formatted
text node. The node are splitted and moved in another order than chrome.

[FIX] DomLayout: altered dom must be invalidate from the generated dom.

---

packages/plugin-dom-editable/src/EventNormalizer.ts
packages/plugin-dom-editable/test/EventNormalizerPointer.test.ts

Prior to this fix, double or triple clicking at `<p>ab cd<b>e[]f</b>gh ij</p>` didn't work. Note that tests should be written for this (and with `<b><i><u>` etc) when there is time, and that current tests are not working as they should (it seems that 'mouse setRange on input (ubuntu chrome)' doesn't work locally while the test passes, and that 'click on border set range at the begin (ubuntu chrome)' passes while it doesn't work locally).

[FIX] EventNormalizer: handle double and triple clicks with nested nodes

---

packages/plugin-fontawesome/src/FontAwesomeDomObjectRenderer.ts
packages/plugin-fontawesome/src/FontAwesomeNode.ts
packages/plugin-fontawesome/src/FontAwesomeXmlDomParser.ts
packages/plugin-fontawesome/test/FontAwesome.test.ts
packages/plugin-xml/src/AttributesDomObjectModifierRenderer.ts
packages/plugin-xml/src/ClassList.ts

And restore them afterwards. This required to rewrite how ClassList
worked in order to keep a history of parsed-then-removed classes to
be able to restore them at their previous position on rendering.

[FIX] FontAwesome: remove FontAwesome classes on parsing

---

packages/plugin-dom-layout/src/DomReconciliationEngine.ts
packages/plugin-dom-layout/test/DomLayout.test.ts

Issue: Dom alteration by an external code or by deletion with a broken
range during a user action. For example the fact of doing backspace
with a selection of the whole DOM not communicated to the VDom.

[FIX] DomLayout: Can redraw an altered text node without content.

---

packages/plugin-dom-layout/src/DomReconciliationEngine.ts
packages/plugin-dom-layout/test/DomLayout.test.ts
packages/plugin-list/src/ListDomObjectRenderer.ts
packages/plugin-list/src/ListItemXmlDomParser.ts
packages/plugin-list/test/List.test.ts

Issue: After insertBreakLine in list, indent in list moves the cursor
outside of the list

[FIX] DomLayout: must keep all origin when redraw a custom node

---

packages/plugin-odoo/src/NoteEditableXmlDomParser.ts
packages/plugin-odoo/src/Odoo.ts

In the signature of Odoo, the content is only based of inline nodes
and the Editor does not yet support properly when that case happen.
For instance, when trying to align the content that does not have
a ContainerNode that is editable, the command will do nothing.
This commit fix that by wrapping all the node inside the default
container of the editor.

[FIX] Odoo: wrap only inlineNode

---

packages/plugin-table/src/TablePickerCellDomObjectRenderer.ts

This is a quick fix: we insert the table on mouseup instead of click. There is a deeper issue that made that close was triggered before click had a chance.

[FIX] Table: properly insert a table on pick a cell in tablepicker

---

packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts

When using  OdooWebsiteEditor, override the keymap CTRL+K
to call `openLinkDialog` rather than `link`.

[IMP] Odoo: shortcut link openLinkDialog

---

packages/plugin-dom-editable/src/DomEditable.ts

_matchCommand might create a new range and need the memory to be open to
do that.

[FIX] DomEditable: encapsulate _matchCommand

---

packages/plugin-xml/src/CssStyle.ts

Before this commit, when parsing a style property with the char ":",
the parsing was incorrect.
For instance "background-image: url(http:whatever)" was parsed as
"background-image: url(http".

[FIX] XML: fix style parsing

---

packages/plugin-font-size/src/FontSizeDomObjectRenderer.ts

There were two conflicting logic to display the input in it's renderer.

[FIX] FontSize: remove duplicated logic for input

---

packages/plugin-dom-editable/src/EventNormalizer.ts
packages/plugin-dom-editable/test/EventNormalizerPointer.test.ts

Prior to this fix, double clicking the first word of a line in an editable that only has one line selected all.
Note: this skips another event normalizer test that gives a false negative.

[FIX] EventNormalizer: do not select all on dbclick first word

---

packages/plugin-odoo/src/OdooStructureNode.ts
packages/plugin-odoo/src/OdooStructureXmlDomParser.ts

When parsing the ContainerNode if we set no child in it, firstChange
will remain false. So the next insertion will not set the property
`dirty`. Which was wrong.
Now we check that the parsing is finish properly.

[FIX] Odoo: check if containernode dirty

---

packages/bundle-odoo-website-editor/odoo-integration.ts

CF: 
> [SGE] opening the media modal when selecting a single character (range a[b]c) create a traceback https://i.imgur.com/kBHg6CR.jpg 
╰─ [SGE] on it

[FIX] Export FontAwesomeNode to fix a traceback in odoo media modal

---

packages/utils/src/isBlock.ts

On Firefox, calling `window.getComputedStyle` on a list item element that is not in the DOM wrongly returns "inline". As a result, some whitespace was not removed where it should have been.
Additionally, the `computedStyle` map was never set so time was lost computing styles that were already computed.
This commit checks whether the node is contained within the document of the current window before computing styles. If it isn't, our only recourse is to check the nodeName. As a side effect, this should save us a few milliseconds of parsing.
We also properly set the cache now, thereby saving a few extra milliseconds.
Addressing the following bug report:
> 12. [QSM - Firefox] Somehow, during the page edition, the footer exploded (I imagine some kind of normalizing the whole DOM that failed?) …

[FIX] isBlock: properly parse formatting space around <li> in Firefox

---

examples/layout/layout.ts

I blame @Goaman for this :smiling_imp:
The editor won't compile without this fix so it's pretty important.

[FIX] Layout: remove extra parenthesis

---

packages/plugin-font-size/src/FontSizeDomObjectRenderer.ts

Addresses:
```
[JKE1-03] Go on homepage, click translate:
editor ui wrongly initiated:
https://i.imgur.com/AA1qej3.png
```

[FIX] FontSize: hide the font size picker on render if needed

---

packages/plugin-dom-editable/src/DomEditable.ts
packages/plugin-dom-editable/src/EventNormalizer.ts
packages/plugin-dom-layout/src/DomLayout.ts
packages/plugin-dom-layout/src/DomLayoutEngine.ts
packages/plugin-html/test/DefaultDomRenderer.test.ts

Addresses:
```
[JKE1-07]     Edit readonly field:
-> double click select the readonly and let think that it is editable (not saved)
https://drive.google.com/file/d/18hpjnzomHaVr8EclKPiaI3PJRYaf8yZk/view
╰─[DMO] I don't understand what we should be seeing in the video. I see you entering edit mode then saving the page. I'm sure I'm missing something but I don't understand what it is.
╰─[AGE] he clicks in the footer in a node that is not editable and:
if you double click in it, you can start typing (with a simple click, the range is properly canceled but apparently double click bypasses the check)
I'm on it.
╰─[AGE] oh man we are actually doing it right in our abstraction but the DOM changes and we don't redraw
```

[IMP] EventNormalizer: redraw editable on keydown in not-editable

---

packages/core/src/JWEditor.ts
packages/core/src/VNodes/AbstractNode.ts
packages/plugin-dom-layout/src/DomLayout.ts
packages/plugin-fontawesome/src/FontAwesomeDomObjectRenderer.ts
packages/plugin-fontawesome/test/FontAwesome.test.ts
packages/utils/src/utils.ts

```html
<p contenteditable>
<a contenteditable="false">text</a>
</p>
```
Prior to this fix, the `contenteditable="false"` was being ignored by `DomLayout` and `FontAwesomeDomObjectRenderer` because it was on a format and not a node.

[FIX] AbstractNode: check contenteditable attribute on formats too

---

packages/plugin-dom-editable/src/EventNormalizer.ts

Prior to this fix, there were certain situations where doing `shift+enter` was triggering an `insertParagraph` action instead of `insertLineBreak`. The reason was that in those situations, the browser was actually giving an `insertText` input type together with the `Enter` key, for some reason...
Steps to reproduce the fixed issue:
- open example Note "Project N.947.5" in Odoo
- add: `Enter` - couple of characters - `Enter` - couple of characters
- make the last line `blockquote`
- at the end of the last line, add: `Shift+Enter` - couple of characters
- Shift+enter at this point broke the `blockquote`.

[FIX] EventNormalizer: consistently apply insertLineBreak on shift+enter

---

packages/plugin-template/assets/Template.css

This is important for mass mailing as otherwise the template picker
doesn't have a scrollbar and there are templates that can't be selected.

[FIX] Template: ensure an overflow on the template container

---

packages/plugin-dom-editable/src/EventNormalizer.ts

Only [shift] + [ENTER] should create a lineBreak
----
7. [FP] randomly inserts <br> instead of <p>, sometimes: https://drive.google.com/file/d/1ABvxKLR76JY1FB1apbd4HtWqOci9E0wq/view
╰─[AGE] can't reproduce on jabberwock demo so it's an integration issue
╰─[SGE] seems to be when the user press ENTER before he release the last keypress

[FIX] EventNormalizer: Don't force a line break with [any key] + [ENTER]

---

packages/core/src/Core.ts
packages/core/test/VDocument.test.ts
packages/plugin-char/test/Char.test.ts

Handles:
[FP] when deleting a paragraph (triple clicks), it sets the line style to the next paragraph: https://drive.google.com/file/d/1dFkex7dZkD4RTAZvUeK8hJa6XPcqiAN1/view

[ADD] Core: handle triple-click delete special case

---

packages/plugin-dom-layout/src/DomLayoutEngine.ts
packages/plugin-dom-layout/src/DomReconciliationEngine.ts

Errors are put in a try catch so that editing continues without jabberwok
detecting that there was an error and doing an undo. Request by fp so
that the code is more "robust" to errors.

[IMP] DomLayout: Some errors are logged without doing an automatic undo

---

packages/plugin-list/src/List.ts
packages/plugin-list/src/ListItemXmlDomParser.ts
packages/plugin-list/test/List.test.ts

Issue: if a list-style add marker in the attributes, this breaks the
rendering of the checklist.

[FIX] List: toggle list should removes list-style from li element

---

packages/plugin-table/assets/tableUI.css

When inactive, the "unlink" button in web_editor has an opacity below one.
This creates a new stacking context, which resets the z-index.
See [this link](https://coder-coder.com/z-index-isnt-working/#3-youre-setting-opacity-transform-or-other-css-properties-that-put-the-element-in-a-new-stacking-context) for more info.
It made the "unlink" button visible even when the table picker was over it.
It was fixed by giving the table picker a higher z-index, default being zero.

[FIX] table: table-picker rendered under some buttons

---

packages/plugin-blockquote/src/Blockquote.ts
packages/plugin-blockquote/test/Blockquote.test.ts
packages/plugin-heading/src/Heading.ts
packages/plugin-heading/test/Heading.test.ts
packages/plugin-pre/src/Pre.ts
packages/plugin-pre/test/Pre.test.ts

`insertParagraphBreak` at the end of a `Heading`, a `Blockquote` or a `Pre` inserts a new default container instead of splitting the
container. This is meant as some sort of edition "reboot": we start a new fresh paragraph. In this context it makes no sense to preserve the modifiers of the container. This commit clears the range modifiers in these cases.

[IMP] Heading, Blockquote, Pre: do not preserve modifiers on end split

---

packages/plugin-textarea/src/TextareaXmlDomParser.ts

Textarea were not parsed correctly when parsed as xml, which happened when loading existing page from the backend.

[FIX] plugin-textarea: use tag name for textarea parser predicate

---

packages/plugin-underline/src/UnderlineFormat.ts
packages/plugin-underline/test/underline.test.ts

The underline style (`text-decoration: underline;`) can be broken if a child element has a css `display: inline-block;`. ( see W3C spec https://www.w3.org/TR/CSS21/text.html#lining-striking-props ).
To combat this we have ton ensure that a `<u>` tag is as deep a possible in the rendered DOM, so he cannot contain other child element expect Characters.
+ Add unit tests

[FIX] Underline: always put <u> as deep as possible in the rendered DOM

---

packages/plugin-dom-layout/src/DomLayout.ts

The screenshot feature on Firefox would trigger an error (right click -> Take a screenshot).

[FIX] DomLayout: firefox screenshot feature

---

packages/core/src/Modifier.ts
packages/core/src/Modifiers.ts
packages/core/src/VRange.ts
packages/core/test/Modifiers.test.ts
packages/plugin-char/test/Char.test.ts
packages/plugin-dom-helpers/src/DomHelpers.ts
packages/plugin-inline/src/Inline.ts
packages/plugin-inline/test/Inline.test.ts
packages/plugin-renderer/src/RenderingEngine.ts

Some modifiers have a cascading effect (e.g.: bold).
Coupled with the fact that some modifiers can have such modifiers themselves (e.g.: a SpanFormat with a bold modifier), it is possible that an effect happens to the range that is not caused by a modifier acting directly on that range.
This commit aims at providing support for the use case while altering the least possible the rest of the code base.
Actual implementation for the existing modifiers that are concerned should come in a later commit.

[IMP] core: add cascading modifier support

---

packages/plugin-odoo/src/OdooStructureNode.ts
packages/plugin-odoo/src/OdooStructureXmlDomParser.ts

A block without the "oe_structure" class but with data-oe-field="arch" should be considered an OdooStructure as it hosts an architecture and contains all the information required in order to save it.
This ensures proper parsing of the form builder snippet in the context of the "contact us" section (in which the form builder snippet is appended outside the .oe_structure).

[IMP] Odoo: expand parsing range of OdooStructureNode

---

packages/bundle-basic-editor/BasicEditor.ts
packages/bundle-odoo-website-editor/OdooWebsiteEditor.ts
packages/plugin-char/test/Char.test.ts
packages/plugin-small/src/Small.ts
packages/plugin-small/src/SmallFormat.ts
packages/plugin-small/src/SmallXmlDomParser.ts
packages/utils/test/formattingSpace.test.ts

Trying to fix the fact that
```html
<div>
<input/>
<small>abc</small>
</div>
```
rendered a non-breakable space between the `input` and the `small`, and after writing some tests, I realized that the cause for the bug was that we didn't actually handle `small` yet. So now we do.

[ADD] Small: handle <small>

---

packages/plugin-backgroundcolor/test/BackgroundColor.test.ts
packages/plugin-color/src/Color.ts
packages/plugin-dom-layout/test/DomLayout.test.ts
packages/plugin-textcolor/src/TextColor.ts

It turns out that the color behavior was not a standard behavior but specific to TextColor (at least in the context of Odoo).
The simpler behavior is now implemented in `Color` and is used by `BackgroundColor` while the specific behavior is implemented in `TextColor` directly.

[FIX] Color, TextColor: fix background color behavior
